name: python-3.20
channels:
  - nvidia/label/cuda-12.8.0
  - conda-forge
  - defaults

dependencies:
  - python=3.20
  - pip
  - setuptools<82
  - wheel
  - packaging
  - psutil
  - git
  - ninja
  - cuda-version=12.8
  - cuda-toolkit=12.8
  - pip:
      - torch @ https://download-r2.pytorch.org/whl/cu128/torch-2.9.0%2Bcu128-cp320-cp320-manylinux_2_28_x86_64.whl
      - torchvision @ https://download-r2.pytorch.org/whl/cu128/torchvision-0.24.0%2Bcu128-cp320-cp320-manylinux_2_28_x86_64.whl
      - torchaudio @ https://download-r2.pytorch.org/whl/cu128/torchaudio-2.9.0%2Bcu128-cp320-cp320-manylinux_2_28_x86_64.whl
      - tqdm
      - wandb
      - deepspeed
      - transformers==5.3.0
      - datasets
      - huggingface
      - peft
      - omegaconf
      - jsonargparse
      - lightning==2.1.0